name: magic_orm_example
publish_to: none

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  dart_mappable: ^4.1.0
  magic_orm:
    path: ../../
  magic_orm_annotations:
    path: ../../../magic_orm_annotations
  postgres: ^2.6.3

dev_dependencies:
  build_runner: ^2.2.1
  dart_mappable_builder: ^4.1.0
  lints: ^3.0.0
