// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by: magic_orm
//
// Define your database with the [@MagicDatabase] annotation using
// these models as follows:
//
// ```
// import 'package:magic_orm_example/models.export.dart';
//
// @MagicDatabase(models: models)
// class Database extends PgDatabase { ... }
// ```

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'models/account.dart' as _i4;
import 'models/address.dart' as _i3;
import 'models/company.dart' as _i5;
import 'models/invoice.dart' as _i1;
import 'models/party.dart' as _i2;

const List<Type> models = [
  _i1.Invoice,
  _i2.Party,
  _i3.BillingAddress,
  _i4.Account,
  _i5.Company,
];
