name: stormberry_example
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  better_stormberry:
    path: ../../better_stormberry
  better_stormberry_annotations:
    path: ../../better_stormberry_annotations
  dart_mappable: ^4.1.0
  postgres: ^2.6.3

dev_dependencies:
  build_runner: ^2.2.1
  dart_mappable_builder: ^4.1.0
  lints: ^3.0.0
